#################################################### 激活配置文件
spring: 
#  mvc:
#    message-codes-resolver-format: postfix-error-code
#    date-format: yyyy-MM-dd
#    static-path-pattern: /resources/**
#  http: 
#    multipart:
#      enabled: true
#      max-file-size: 50
#      max-request-size: 50
      
#  messages:
#    basename: messages # 指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
#    cache-seconds: -1  # 设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
#    encoding: UTF-8    # 设定Message bundles的编码，默认: UTF-8
      
#  output:
#    ansi:
#      enabled: ALWAYS # If your terminal supports ANSI, color output will be used to aid readability. 
  profiles: 
    active:
    - dev

#################################################### Shiro 配置
shiro: 
  userNativeSessionManager: false
  sessionManager: 
    sessionIdUrlRewritingEnabled: false
    globalSessionTimeout: 3600000       
  loginUrl: /login                     # 登陆地址
  successUrl: /index                   # 登陆成功后的地址
  unauthorizedUrl: /unauthorized       # 未授权重定向地址
  web: 
    enabled: true  #是否为 web环境
    
    
#################################################### 日志配置    
logging: 
  config: classpath:log4j2.xml   #日志文件配置路径
  
  
fs: 
  upload:  
    basepath: D:/qianduan 
